// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4J7NPwMa3tw8MQKl8uF1VE0MCdqvWjxQ',
    appId: '1:204370033849:android:eebe56ec062ad54d9f6f68',
    messagingSenderId: '204370033849',
    projectId: 'taskly-f5f91',
    storageBucket: 'taskly-f5f91.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFabSO7uo1PjcrMkg_04TKdb8ZhOhvjSY',
    appId: '1:204370033849:ios:fe3430f25ef81adf9f6f68',
    messagingSenderId: '204370033849',
    projectId: 'taskly-f5f91',
    storageBucket: 'taskly-f5f91.appspot.com',
    iosBundleId: 'com.example.taskly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALCgBz3Eyv2YafGwKDbZrECy68oXYbcTo',
    appId: '1:204370033849:web:08f3ed90578990f39f6f68',
    messagingSenderId: '204370033849',
    projectId: 'taskly-f5f91',
    authDomain: 'taskly-f5f91.firebaseapp.com',
    storageBucket: 'taskly-f5f91.appspot.com',
    measurementId: 'G-XJW3F4ZL7M',
  );
}
